### ISSUE TITLE
Include Java 8 Compatibility

### ISSUE THREAD

**Issue by RubenVerg** [FabricMC/fabric-language-scala#11]
[Java 8 Compatibility](https://github.com/scala/scala-java8-compat) adds helpful methods for converting Scala stuff into Java stuff, and obviously MC wants the java ones.

**Comment by modmuss50** [comment]
Seems reasonable 👍

**Comment by RubenVerg** [comment]
:​)

**Comment by darkstar01** [comment]
I really would love to see this fixed, I want to try realistic water physics mod for fabric but it requires this mod, but it hasn't been updated so I can't try it yet. Please fix this <3

**Comment by darkstar01** [comment]
This is the mod I'm speaking about...  https://www.curseforge.com/minecraft/mc-mods/fluid-physics

**Comment by zml2008** [comment]
This has no impact for you as a mod user. `fabric-language-scala` will work on any version of minecraft.

**Comment by modmuss50** [comment]
Added for the next version.
