### ISSUE TITLE
Scala 2.13.6?

### ISSUE THREAD

**Issue by ChAoSUnItY** [FabricMC/fabric-language-scala#15]
According to Scala's JDK compatibility table, JDK 16 which 1.17's minimum required JDK version is recommended to have 2.13.6 for this moment, any plan to update scala version before scala 3 is out?

**Comment by modmuss50** [comment]
I can look into that, scala 3 seems to be blocked behind gradle support, so it does seem a good idea to update it now. 👍

**Comment by modmuss50** [comment]
Easily done: https://github.com/FabricMC/fabric-language-scala/commit/d9a2919851609ca50283a4f0605ff37ab85196d0

Will get a release out now.
