### ISSUE TITLE
Add Fabric tag to curseforge project

### ISSUE THREAD

**Issue by ChAoSUnItY** [FabricMC/fabric-language-scala#16]
Due to curseforge update, every projects based on fabric loader should tag with fabric in order to make users to download them on curseforge client.

EDIT: You can only download it through curseforge project website, unavailable on curseforge client.

**Comment by katubug** [comment]
Similar issue! This mod downloaded from CurseForge app as a required dependency of another mod, but the app shows it as for an incorrect modloader and directs users to [this page](https://support.curseforge.com/en/support/solutions/articles/9000202116-modloaders-forge-and-fabric-).

**Comment by haykam821** [comment]
The Fabric category no longer exists.

**Comment by katubug** [comment]
I see, so the issue is just on curseforge's side? That tracks, lmao. Thanks
for your help!

**Comment by mschae23** [comment]
> The Fabric category no longer exists.

They probably meant the "Mod Loader" field you have to fill out when uploading a file.

**Comment by Player3324** [comment]
Still needs to be added to the game version

**Comment by modmuss50** [comment]
Edited the existing version, there is still dev work to be done.
