### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by ttramdriver** [FabricMC/fabric-language-scala#19]
the mod is not working for 1.18.2, when i launch the game it wont launch

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
