### ISSUE TITLE
Support automatic pickling of network packet data

### ISSUE THREAD

**Issue by magneticflux-** [FabricMC/fabric-language-scala#4]
[µPickle](http://www.lihaoyi.com/upickle/) is one possibility.

This would make it easy to send packets without having to manually read/write to the byte buffer.

This would also be useful in the Kotlin language module, and could even be adapted to the core network API.

**Comment by magneticflux-** [comment]
It looks like [Crochet](https://github.com/raphydaphy/Crochet) implements something similar to what exists in [TheOneProbe](https://github.com/McJtyMods/TheOneProbe/tree/fabric/src/main/java/mcjty/theoneprobe/network) already, which is a 'handler' implementation and a serialization interface `IPacket`.

Some other network implementations:
* [CC-Tweaked](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.14-fabric/src/main/java/dan200/computercraft/shared/network/NetworkMessage.java) (A full 'handler' implementation)
* [InfraRedstone](https://github.com/elytra/InfraRedstone-Fabric/blob/1.14/src/main/java/com/elytradev/infraredstone/util/InfraRedstoneNetworking.java) (Working with raw buffers)
* [JustSleep](https://github.com/modmuss50/JustSleep/blob/1.14/src/main/java/me/modmuss50/justsleep/JustSleep.java#L67) (Working with raw buffers)

**Comment by modmuss50** [comment]
I think this is somewhat out of scope for this lang adapter.
