### ISSUE TITLE
Question: Why not include dependencies as Jar in Jar

### ISSUE THREAD

**Issue by jaideepheer** [FabricMC/fabric-language-scala#8]
I noticed that this mod shadows the scala libraries. I feel that a better approach would be to include these libraries as Jar in Jar so that the loader can better manage the versioning of each library individually.

I just feel JiJ to be a safer approach.

**Comment by asiekierka** [comment]
The way we do it, JiJ is only of use when the library exists in the form of a Fabric mod with its own upstream. See [this helpful chart](https://fabricmc.net/wiki/tutorial:loader04x). In fabric-language-scala's case, the mod "fabric-language-scala" currently serves as the upstream for those libraries.

**Comment by jaideepheer** [comment]
But with this approach the library versions are frozen relative to each other. Also what if I want to include a different lib. that uses one of the shaded libs? Won't I be forced to shade this new lib. because of the classpath difference of the standard libs included here.
